kafka:
  consumer:
    topic: test-histrack-1
    clientIdPrefix: temperature-data-push
    bootstrap-servers: kafka01:9092,kafka02:9092,kafka03:9092
    group-id: temperature-data-push
    auto-offset-reset: earliest
    enable-auto-commit: false
    auto-commit-interval: 1000
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    max-poll-records: 500
    fetch-min-bytes: 1
    fetch-max-wait: 1000
#container
    concurrency: 3
    batchListener: true