server:
  port: 9000
  shutdown: immediate
  servlet:
    context-path: /
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
spring:
  jmx:
    default-domain: /dispatcher
eureka:
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://admin:123@eureka/eureka
  instance:
    instance-id: third-push-dispatcher
    prefer-ip-address: true
